name: Twobridge pipeline

# Trigger the workflow on push or pull-requests to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4  # Use the latest checkout action

      # Set up Node.js
      - name: Set up Node.js v21.x
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          cache: 'npm'  # Cache npm dependencies to speed up builds

      # Cache node_modules to avoid re-installing on other jobs
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Install dependencies using npm ci for faster and more reliable installs
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build project
        run: npx nest build

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures it runs only after the build job completes
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run the tests with Jest
      - name: Run tests
        run: npx jest

      # Run tests with code coverage
      - name: Run tests with coverage
        run: npx jest --coverage
